name: Kube Linter

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  kube-linter:
    name: Run kube-linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run kube-linter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: ./k8s

      - name: Run kube-linter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: ./k8s-sealed-secret

      - name: Kustomize Build dev
        uses: karancode/kustomize-github-action@v1.0.0
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: 'k8s/overlays/dev'
          kustomize_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Kustomize Build dev
        uses: karancode/kustomize-github-action@v1.0.0
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: 'k8s/overlays/prod'
          kustomize_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}